#!/bin/bash
version="develop-SNAPSHOT"
localPath="/home/thealmikey/IdeaProjects/2zilla/manager/$wrappedPath/.m2/repository/io/aklivity/zilla/manager/develop-SNAPSHOT/manager-develop-SNAPSHOT.jar"
wrappedPath=".zpm/wrapper/manager-develop-SNAPSHOT.jar"

if [ ! -r "$wrappedPath" ]; then
  mkdir -p "$(dirname "$wrappedPath")"
  if [ -r "$localPath" ]; then
    echo "$wrappedPath not found, copying from $localPath"
    cp "$localPath" "$wrappedPath"
  else
    echo "Error: $localPath not found. Please run 'mvn install' for manager first."
    exit 1
  fi
fi

exec java -jar "$wrappedPath" "$@"