name: Build and Publish Docker Image

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    environment: Zilla Env
    steps:
      - name: Checkout GitHub sources
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Debug Secret
        run: |
          if [ -n "${{ secrets.CR_PAT }}" ]; then
            echo "CR_PAT set: Yes"
          else
            echo "CR_PAT set: No"
          fi

      - name: Build with Maven (Skip Tests)
        run: ./mvnw -B -U -nsu -DskipTests=true -Dmaven.test.skip=true -Dmaven.dependency.skip.test=true -Ddocker.logStdout=true -Ddocker.skip.push=false -Ddocker.verbose=true -Dcheckstyle.skip=true -Dlicense.skip=true install -X
        env:
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Debug Docker Images
        run: |
          docker images --format "{{.Repository}}:{{.Tag}}" | grep "zillali" || echo "No zillali image found"
          docker images
          if [ -f cloud/docker-image/src/main/docker/assembly.xml ]; then cat cloud/docker-image/src/main/docker/assembly.xml; else echo "assembly.xml not found"; fi
          if [ -f cloud/docker-image/src/main/docker/zpm.json ]; then cat cloud/docker-image/src/main/docker/zpm.json; else echo "zpm.json not found"; fi

      - name: Save Docker image
        if: success()
        run: |
          mkdir -p ~/docker-cache
          docker save -o ~/docker-cache/docker.tar ghcr.io/thealmikey/zillali:develop-SNAPSHOT || echo "Failed to save Docker image"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Conditional Artifact Upload
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: zilla-build-${{ github.event.number }}
          path: |
            **/hs_err_pid*.log
            **/target/surefire-reports/
            **/target/zilla-itests/
            **/target/failsafe-reports/